version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: maxsusi
      POSTGRES_PASSWORD: P@ssw0rd++
      POSTGRES_DB: videoranDB
    ports:
      - "5432:5432"  # Maps port 5432 on the host to port 5432 in the container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: maxsusi@admin.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd++
    ports:
      - "8080:80"  # Maps port 8080 on the host to port 80 in the container
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: